apiVersion: v1
kind: Service
metadata:
    name: prometheus-service
    namespace: monitoring
spec:
    selector:
      app: prometheus
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
