apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-stub-status-conf
  namespace: monitoring
data:
  nginx.conf: |
    server {
        listen 80;
        location /stub_status {
            stub_status;
            allow all;
        }
    }
